/*
| Frases visíveis/faladas do app da criança que não vêm do conteúdo: curtas,
| sem diminutivos, tom de missão espacial. Telas novas leem daqui; as antigas
| migram conforme são tocadas.
*/
export const COPY = {
  galaxia: {
    titulo: "Galáxia",
    ola: (apelido: string) => `Oi, ${apelido}!`,
    instrucao: "Escolha um planeta ou uma missão do dia.",
    erro: "Não consegui abrir a Galáxia. Toque no botão para tentar de novo.",
    escolhasDoDia: "Missões do dia",
    planetas: "Planetas",
    emBreve: "Em breve",
    amigos: "Base dos amigos",
    perfil: "Meu perfil",
    revisao: "Revisão",
  },
  planeta: {
    voltar: "Voltar à Galáxia",
    instrucao: (nome: string) => `Planeta ${nome}. Escolha a sua missão.`,
    erro: "Não consegui abrir o planeta. Toque no botão para tentar de novo.",
    vazio: "Ainda não tem missão neste planeta. Volte logo!",
    trancada: "Essa missão ainda está trancada. Termine a anterior.",
    teia: "Minha Teia de Palavras",
  },
  missao: {
    voltar: "Voltar ao planeta",
    trancada: "Essa missão ainda está trancada",
    falha: "Não consegui abrir a missão. Vamos tentar de novo?",
    concluida: "Missão concluída!",
    proxima: "Próxima missão",
    proximoEpisodio: "Próximo episódio",
  },
  nivel: {
    subiu: (nivel: number) => `Você subiu para o nível ${nivel}!`,
    fechar: "Continuar",
  },
  amigos: {
    titulo: "Base dos amigos",
    instrucao: "Aqui chegam as aulas dos seus amigos. Toque numa aula para jogar, ou dê uma aula você.",
    erro: "Não consegui abrir a base dos amigos. Toque no botão para tentar de novo.",
    voltar: "Voltar à base dos amigos",
    recebidas: "Aulas dos amigos",
    semAulas: "Ainda não chegou aula de amigo.",
    minhas: "Minhas aulas",
    semMinhas: "Você ainda não deu uma aula.",
    darAula: "Dar uma aula",
    darAulaSobre: (rotulo: string) => `Dar uma aula sobre ${rotulo}`,
    nova: "nova",
    feita: "feita",
    ouvir: "Ouvir a aula",
    responder: "Responder",
    ouvirInstrucao: (apelido: string) => `Aula de ${apelido}. Toque para ouvir, depois responda.`,
    reagirInstrucao: "O que você achou? Toque numa reação.",
    reacoes: { valeu: "Valeu", aprendi: "Aprendi", top: "Top" },
    reacaoEnviada: (apelido: string) => `Sua reação foi para ${apelido}.`,
    escolherMissao: "Sobre qual missão é a sua aula?",
    escolherModelo: "Escolha o desafio da sua aula. Toque para ouvir.",
    semModelos: "Essa missão ainda não tem desafio para dar aula.",
    outro: "Outro desafio",
    gravarInstrucao: "Explique como você resolve. Depois seus amigos tentam.",
    gravar: "Gravar",
    parar: "Parar",
    gravando: "Gravando",
    ouvirGravacao: "Ouvir minha gravação",
    gravarDeNovo: "Gravar de novo",
    enviar: "Enviar aula",
    enviada: "Sua aula foi para um adulto olhar.",
    enviadaDetalhe: "Quando for aprovada, ela chega aos seus amigos.",
    semMicrofone: "Não achei o microfone. Peça ajuda a um adulto.",
    status: { pendente: "esperando um adulto", aprovada: "chegou aos amigos", recusada: "não foi dessa vez" },
  },
  roda: {
    titulo: "Roda",
    entrar: (rotulo: string) => `Entrar na roda: ${rotulo}`,
    aberta: "Roda aberta",
    sair: "Sair da roda",
    esperando: "Esperando o educador começar. Quem já chegou aparece aqui.",
    chegou: (n: number) => (n === 1 ? "1 criança na roda" : `${n} crianças na roda`),
    semRoda: "Não achei uma roda aberta para você. Peça ao educador para abrir uma.",
    erro: "Não consegui entrar na roda. Toque no botão para tentar de novo.",
    seguir: "Espere o educador seguir para a próxima etapa.",
    conquista: "Missão da roda concluída! Espere o educador encerrar.",
    acabou: "A roda acabou! A missão ficou concluída para você.",
    suaVez: (parceiro: string) => `Sua vez. ${parceiro} vai conferir a sua resposta.`,
    vezDe: (parceiro: string) => `Vez de ${parceiro}. Espere a proposta.`,
    esperandoPar: (parceiro: string) => `Esperando ${parceiro} responder…`,
    propos: (parceiro: string, descricao: string) => `${parceiro} propôs: ${descricao}.`,
    concordo: "Concordo",
    mudar: "Vamos mudar",
    dupla: (parceiro: string) => `Sua dupla é ${parceiro}.`,
    semDupla: "Você está sem dupla nesta roda: jogue sozinho.",
  },
  comum: {
    continuar: "Continuar",
    proximo: "Próximo",
    tentarDeNovo: "Tentar de novo",
    ouvirDeNovo: "Ouvir de novo",
    voltar: "Voltar",
    pontos: (n: number) => (n === 1 ? "1 ponto" : `${n} pontos`),
  },
} as const;
